export default {
    overlay : document.getElementById("overlay"),
    loginBtn : document.getElementById("login_button"),
    modalWrap : document.getElementById("modal__wrap"),
    loginForm : document.getElementById("loginModal"),
    loginInput : document.getElementById("loginModal__login"),
    successMsg : document.getElementById("successMsg"),
    errorModal : document.getElementById("error"),
    errorBlock : document.getElementById("errMsg"),
    callbackBtn : document.getElementById("callbackBtn"),
    registerBtn : document.getElementById("register_button"),
    successForm : document.getElementById("successForm"),
    callbackForm : document.getElementById("callback"),
    passwordInput : document.getElementById("loginModal__password"),

    emptyError : "Field cannot be empty, please try again",
    existsError : "User with this login already exists",
    successLogin : "Welcome",
    incorrectError : "Login or password does not match any account, please try again",
    successRegister : "Your account has been create successfully!",

    orderSum : document.getElementById("orderSum"),
    orderBtn : document.getElementById("btnOrder"),
    orderWrap : document.getElementById("orderWrap"),
    clearOrder : document.getElementById("clearOrder"),
    overBasket : document.getElementById("overBasket"),
    basketList : document.getElementById("basketList"),
    summaryPrice : undefined,
}